runtime: custom
env: flex

beta_settings:
    cloud_sql_instances: smart-grin-262119:europe-west1:filmdemocracy-dev

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
