version: '3.7'

services:

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    hostname: postgresdb
    env_file:
      - ./secrets/postgresdb.env
    volumes:
      - ./local/data/postgresdb/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    env_file:
      - ./secrets/mongodb.env
    volumes:
      - ./local/data/mongodb/backups:/backups
      - ./local/data/mongodb/db:/data/db
    ports:
      - 27017:27017

  web:
    build: .
    container_name: filmdemocracy
    hostname: filmdemocracy
    volumes:
      - .:/code:z
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
      - mongodb
