version: '3'

services:

  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command: /cloud_sql_proxy --dir=/cloudsql -instances=smart-grin-262119:europe-west1:filmdemocracy-dev=tcp:0.0.0.0:5432 -credential_file=./secrets/cloudsql-credentials.json
    ports:
      - 5432:5432
    volumes:
      - ./secrets/cloudsql-credentials.json:/secrets/cloudsql-credentials.json

  web:
    build: .
    volumes:
      - .:/code:z
    ports:
      - 8080:8080
    depends_on:
      - cloudsql-proxy
