# Generated by Django 2.1.4 on 2019-01-03 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filmdemocracy.socialclub.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='Club name')),
                ('short_description', models.TextField(max_length=100, verbose_name='Short club description')),
                ('club_rules', models.TextField(blank=True, default='', max_length=324, null=True, verbose_name='Club rules (optional)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=filmdemocracy.socialclub.models.get_club_image_path, verbose_name='club image')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
