from django.urls import path
from django.contrib.auth import views as auth_views

from filmdemocracy.registration import views

app_name = 'registration'
urlpatterns = [
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup'
    ),
    path(
        'account_info/',
        views.AccountInfoView.as_view(),
        name='account_info'
    ),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='registration/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        'del_account_conf/',
        views.DelAccountConfirmView.as_view(),
        name='del_account_conf'
    ),
    path(
        'del_account/',
        views.del_account,
        name='del_account'
    ),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            success_url='/registration/password_change/done/',
            template_name='registration/password_change.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/password_change_done.html'
        ),
        name='password_change_done'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            success_url='/registration/password_reset/done/',
            html_email_template_name='registration/password_reset_email.html',
            template_name='registration/password_reset.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='registration/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url='/registration/reset/done/',
            template_name='registration/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]
