# Generated by Django 2.1.4 on 2019-01-03 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialclub', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('seen', models.BooleanField(default=False)),
                ('seen_date', models.DateField(blank=True, null=True, verbose_name='date seen')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialclub.Club')),
            ],
        ),
        migrations.CreateModel(
            name='FilmDb',
            fields=[
                ('imdb_id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='IMDb id')),
                ('faff_id', models.CharField(default='', max_length=6, verbose_name='FilmAffinity id')),
                ('title', models.CharField(default='', max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('rated', models.CharField(default='', max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('director', models.CharField(default='', max_length=100)),
                ('writer', models.CharField(default='', max_length=200)),
                ('actors', models.CharField(default='', max_length=300)),
                ('poster_url', models.URLField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=100)),
                ('language', models.CharField(default='', max_length=20)),
                ('plot', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField(auto_now_add=True, verbose_name='date of vote')),
                ('choice', models.CharField(choices=[('omg', 'I really really want to see it.'), ('yes', 'I want to see it.'), ('seenok', "I've seen it, but I wouldn't mind seeing it again."), ('meh', 'Meh...'), ('no', "I don't want to see it."), ('seenno', "I've seen it, and I don't want to see it again."), ('veto', 'Veto!')], max_length=6)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracy.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='filmdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracy.FilmDb'),
        ),
        migrations.AddField(
            model_name='film',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
