# Generated by Django 2.1.4 on 2018-12-16 23:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('imdb_id', models.CharField(default='', max_length=10, verbose_name='IMDb id')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('seen', models.BooleanField(default=False)),
                ('seen_date', models.DateField(blank=True, null=True, verbose_name='date seen')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date of vote')),
                ('choice', models.CharField(choices=[('veto', 'Veto!'), ('seenno', "I've seen it and I don't want to see it again."), ('no', "I don't want to see it."), ('meh', 'Meh...'), ('seenok', "I've seen it and I wouldn't mind seeing it again."), ('yes', 'I want to see it.'), ('omg', 'I really want to see it.')], default='meh', max_length=7)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracy.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
